blank_issues_enabled: false
contact_links:
  - name: Report a problem with PyPy
    url: https://github.com/pypy/pypy/issues
    about: Also see https://www.pypy.org/contact.html to reach the PyPy team.
